### ISSUE TITLE
Redmine "Internal error" when trying to close the issue that is on todo list

### ISSUE THREAD

**Issue by macmacy** [ande3577/redmine-stuff-to-do-plugin#45]
Steps to reproduce:
- On Stuff To Do page, drag issue onto "What I'm doing now" pane
- Click on issue ID to go to issue page.
- Select "Update", change status to "Closed" and press "Submit"
- Redmine error page is displayed

The issue is not closed (stays in previous state).
It is not necessary to click go to issue page from Stuff To Do - it is enough that issue is at "What I'm doing now" list and you cannot close it.
If you move back the issue to "What's available" pane, it closes fine.

In redmine log I have:

```
NoMethodError (undefined method `index' for #<User:0xb418f984>):
  app/models/mailer.rb:434:in `deliver_mail'
  app/models/issue.rb:884:in `save_issue_with_child_records'
  app/models/issue.rb:871:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:171:in `update'
```

Redmine running at Debian squeeze. Redmine config:

```
Environment:
  Redmine version                          2.1.2.stable
  Ruby version                             1.8.7 (i486-linux)
  Rails version                            3.2.8
  Environment                              production
  Database adapter                         MySQL
Redmine plugins:
  jredmine                                 1.5.1
  projects_tree_view                       0.0.8
  redmine_backlogs                         v0.9.26
  redmine_default_assign                   0.2.0
  redmine_dmsf                             1.4.5 stable
  redmine_favourite_projects               0.6.1
  redmine_gitolite_hook                    0.1.1
  redmine_importer                         1.0
  redmine_my_roadmaps                      0.1.12_redmine2.1
  redmine_plugin_views_revisions           0.0.1
  redmine_private_wiki                     0.2.2
  redmine_testlinklink                     1.0.0
  redmine_wiki_extensions                  0.6.0
  redmine_xls_export                       0.2.1
  redmine_xnet_bugzilla                    0.0.1
  stuff_to_do_plugin                       0.4.1
```

**Comment by ande3577** [comment]
I'll take a look at this when I get a chance.

Do you have a notification address set in the plugin settings? If not that might be creating an error.

As a temporary workaround, setting the plugin settings to -1 will disable email notification and let you test out the other areas of the plugin.

**Comment by macmacy** [comment]
On 2013-11-15 14:43, David S Anderson wrote:

> I'll take a look at this when I get a chance.
> 
> Do you have a notification address set in the plugin settings? If not
> that might be creating an error.
> 
> As a temporary workaround, setting the plugin settings to -1 will
> disable email notification and let you test out the other areas of 
> the
> plugin.

YES, that was the problem! I've set threshold to -1 and error has gone.
And I actually don't need this notification, so for me the workaround 
is just fine.
Thanks for quick response,
Maciej
